# Replace YOUR_APP with the heroku app name and YOUR_TOKEN with the
# same token used in private_pub.yml of your rails project.

development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://ue-fayeserver.herokuapp.com/faye"
  secret_token: "b14fd3e89de92fbf00e6ac2e51dba49d83e54d22b87df40fc22249d32ac970dc"
